/**
 * INCLAW Code Sandbox
 *
 * Provides safe code execution environment for testing generated code.
 * Uses WebContainer API concepts for browser-based execution
 * and server-side Docker sandboxing for production.
 */

export interface SandboxFile {
  path: string;
  content: string;
  language?: string;
}

export interface SandboxProject {
  id: string;
  name: string;
  template: string;
  files: SandboxFile[];
  status: "idle" | "running" | "building" | "error";
  previewUrl?: string;
  createdAt: number;
}

export interface ExecutionResult {
  stdout: string;
  stderr: string;
  exitCode: number;
  duration: number;
  output?: string;
}

export interface PreviewConfig {
  port: number;
  command: string;
  env?: Record<string, string>;
}

/** Project templates with starter files */
export const PROJECT_TEMPLATES: Record<string, { files: SandboxFile[]; preview: PreviewConfig }> = {
  nextjs: {
    files: [
      {
        path: "package.json",
        content: JSON.stringify(
          {
            name: "inclaw-app",
            private: true,
            scripts: { dev: "next dev", build: "next build", start: "next start" },
            dependencies: { next: "latest", react: "latest", "react-dom": "latest" },
            devDependencies: { typescript: "latest", "@types/react": "latest", "@types/node": "latest" },
          },
          null,
          2
        ),
      },
      {
        path: "src/app/page.tsx",
        language: "typescript",
        content: `export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-900 to-black text-white">
      <div className="text-center">
        <h1 className="text-5xl font-bold mb-4">🚀 Built with INCLAW</h1>
        <p className="text-xl text-gray-400">Your AI-generated application is ready!</p>
      </div>
    </main>
  );
}`,
      },
      {
        path: "src/app/layout.tsx",
        language: "typescript",
        content: `export const metadata = { title: 'INCLAW App', description: 'Generated by INCLAW AI' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
      },
    ],
    preview: { port: 3000, command: "npm run dev" },
  },

  react: {
    files: [
      {
        path: "package.json",
        content: JSON.stringify(
          {
            name: "inclaw-react-app",
            private: true,
            scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
            dependencies: { react: "latest", "react-dom": "latest" },
            devDependencies: { vite: "latest", "@vitejs/plugin-react": "latest", typescript: "latest" },
          },
          null,
          2
        ),
      },
      {
        path: "index.html",
        language: "html",
        content: `<!DOCTYPE html>
<html lang="en">
  <head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>INCLAW App</title></head>
  <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>
</html>`,
      },
      {
        path: "src/main.tsx",
        language: "typescript",
        content: `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode><App /></React.StrictMode>
);`,
      },
      {
        path: "src/App.tsx",
        language: "typescript",
        content: `import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', background: '#0a0a0a', color: '#fff' }}>
      <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>🚀 INCLAW React App</h1>
      <button onClick={() => setCount(c => c + 1)} style={{ padding: '12px 24px', fontSize: '1.2rem', background: '#06b6d4', border: 'none', borderRadius: '8px', color: '#fff', cursor: 'pointer' }}>
        Count: {count}
      </button>
    </div>
  );
}`,
      },
    ],
    preview: { port: 5173, command: "npm run dev" },
  },

  express: {
    files: [
      {
        path: "package.json",
        content: JSON.stringify(
          {
            name: "inclaw-api",
            private: true,
            scripts: { dev: "tsx watch src/index.ts", build: "tsc", start: "node dist/index.js" },
            dependencies: { express: "latest", cors: "latest", helmet: "latest" },
            devDependencies: { typescript: "latest", tsx: "latest", "@types/express": "latest", "@types/cors": "latest" },
          },
          null,
          2
        ),
      },
      {
        path: "src/index.ts",
        language: "typescript",
        content: `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';

const app = express();
app.use(helmet());
app.use(cors());
app.use(express.json());

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', message: 'INCLAW API running', timestamp: new Date().toISOString() });
});

app.get('/api/items', (req, res) => {
  res.json([
    { id: 1, name: 'Item 1', description: 'First item' },
    { id: 2, name: 'Item 2', description: 'Second item' },
  ]);
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(\`🚀 INCLAW API running on http://localhost:\${PORT}\`));`,
      },
    ],
    preview: { port: 3001, command: "npm run dev" },
  },

  "static-html": {
    files: [
      {
        path: "index.html",
        language: "html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>INCLAW Site</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; background: #0a0a0a; color: #fff; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
    .container { text-align: center; }
    h1 { font-size: 3rem; margin-bottom: 1rem; background: linear-gradient(135deg, #06b6d4, #a855f7); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    p { color: #9ca3af; font-size: 1.2rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Built with INCLAW ⚡</h1>
    <p>Your AI-generated website is live!</p>
  </div>
</body>
</html>`,
      },
    ],
    preview: { port: 8080, command: "npx serve ." },
  },

  fastapi: {
    files: [
      {
        path: "requirements.txt",
        content: "fastapi\nuvicorn[standard]\npydantic",
      },
      {
        path: "main.py",
        language: "python",
        content: `from fastapi import FastAPI
from pydantic import BaseModel
from datetime import datetime

app = FastAPI(title="INCLAW API", version="1.0.0")

class Item(BaseModel):
    name: str
    description: str = ""

items: list[dict] = []

@app.get("/")
async def root():
    return {"message": "INCLAW API running", "timestamp": datetime.now().isoformat()}

@app.get("/api/items")
async def list_items():
    return items

@app.post("/api/items")
async def create_item(item: Item):
    new_item = {"id": len(items) + 1, **item.model_dump(), "created_at": datetime.now().isoformat()}
    items.append(new_item)
    return new_item

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)`,
      },
    ],
    preview: { port: 8000, command: "uvicorn main:app --reload" },
  },

  flask: {
    files: [
      {
        path: "requirements.txt",
        content: "flask\nflask-cors",
      },
      {
        path: "app.py",
        language: "python",
        content: `from flask import Flask, jsonify, request
from flask_cors import CORS
from datetime import datetime

app = Flask(__name__)
CORS(app)

items = []

@app.route('/')
def index():
    return jsonify(message="INCLAW Flask API", timestamp=datetime.now().isoformat())

@app.route('/api/items', methods=['GET'])
def list_items():
    return jsonify(items)

@app.route('/api/items', methods=['POST'])
def create_item():
    data = request.get_json()
    item = {'id': len(items) + 1, 'name': data['name'], 'description': data.get('description', ''), 'created_at': datetime.now().isoformat()}
    items.append(item)
    return jsonify(item), 201

if __name__ == '__main__':
    app.run(debug=True, port=5000)`,
      },
    ],
    preview: { port: 5000, command: "python app.py" },
  },

  vue: {
    files: [
      {
        path: "package.json",
        content: JSON.stringify(
          {
            name: "inclaw-vue-app",
            private: true,
            scripts: { dev: "vite", build: "vite build" },
            dependencies: { vue: "latest" },
            devDependencies: { vite: "latest", "@vitejs/plugin-vue": "latest" },
          },
          null,
          2
        ),
      },
      {
        path: "index.html",
        language: "html",
        content: `<!DOCTYPE html>
<html lang="en">
  <head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>INCLAW Vue App</title></head>
  <body><div id="app"></div><script type="module" src="/src/main.ts"></script></body>
</html>`,
      },
      {
        path: "src/main.ts",
        language: "typescript",
        content: `import { createApp } from 'vue';\nimport App from './App.vue';\ncreateApp(App).mount('#app');`,
      },
      {
        path: "src/App.vue",
        language: "vue",
        content: `<template>
  <div class="app">
    <h1>🚀 INCLAW Vue App</h1>
    <button @click="count++">Count: {{ count }}</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
const count = ref(0);
</script>

<style scoped>
.app { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; background: #0a0a0a; color: #fff; }
h1 { font-size: 3rem; margin-bottom: 1rem; }
button { padding: 12px 24px; font-size: 1.2rem; background: #06b6d4; border: none; border-radius: 8px; color: #fff; cursor: pointer; }
</style>`,
      },
    ],
    preview: { port: 5173, command: "npm run dev" },
  },
};

/** Create a new sandbox project */
export function createSandboxProject(name: string, template: string): SandboxProject {
  const tmpl = PROJECT_TEMPLATES[template] || PROJECT_TEMPLATES["static-html"];

  return {
    id: `proj_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    name,
    template,
    files: tmpl.files.map((f) => ({ ...f })),
    status: "idle",
    createdAt: Date.now(),
  };
}

/** Update a file in the project */
export function updateProjectFile(project: SandboxProject, path: string, content: string): SandboxProject {
  const existing = project.files.findIndex((f) => f.path === path);
  if (existing >= 0) {
    project.files[existing] = { ...project.files[existing], content };
  } else {
    project.files.push({ path, content });
  }
  return { ...project };
}

/** Delete a file from the project */
export function deleteProjectFile(project: SandboxProject, path: string): SandboxProject {
  project.files = project.files.filter((f) => f.path !== path);
  return { ...project };
}
