"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { nightOwl } from "react-syntax-highlighter/dist/esm/styles/prism";
import { Copy, Check, ChevronRight, Cpu } from "lucide-react";
import { DEMO_CONVERSATIONS } from "@/lib/constants";

export default function DemoSection() {
  const [activeDemo, setActiveDemo] = useState(0);
  const [copied, setCopied] = useState(false);

  const current = DEMO_CONVERSATIONS[activeDemo];

  const handleCopy = () => {
    navigator.clipboard.writeText(current.response);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section id="demo" className="relative py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center"
        >
          <h2 className="text-sm font-semibold uppercase tracking-widest text-orange-400">
            See It In Action
          </h2>
          <p className="mt-3 text-3xl font-bold text-white sm:text-4xl lg:text-5xl">
            INCLAW{" "}
            <span className="bg-gradient-to-r from-orange-400 to-cyan-400 bg-clip-text text-transparent">
              Writes Real Code
            </span>
          </p>
        </motion.div>

        {/* Demo tabs */}
        <div className="mt-12 flex flex-wrap justify-center gap-3">
          {DEMO_CONVERSATIONS.map((demo, i) => (
            <button
              key={i}
              onClick={() => setActiveDemo(i)}
              className={`rounded-lg border px-4 py-2 text-sm transition-all ${
                activeDemo === i
                  ? "border-orange-500/50 bg-orange-500/10 text-orange-300"
                  : "border-white/10 text-slate-400 hover:border-white/20 hover:text-white"
              }`}
            >
              {demo.language.charAt(0).toUpperCase() + demo.language.slice(1)}
            </button>
          ))}
        </div>

        {/* Demo display */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mx-auto mt-8 max-w-4xl"
        >
          <AnimatePresence mode="wait">
            <motion.div
              key={activeDemo}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="overflow-hidden rounded-2xl border border-white/10 bg-[#0a0625]"
            >
              {/* Prompt */}
              <div className="flex items-start gap-3 border-b border-white/5 px-6 py-4">
                <ChevronRight className="mt-0.5 h-5 w-5 shrink-0 text-orange-400" />
                <p className="text-sm text-slate-300">{current.prompt}</p>
              </div>

              {/* Model badge + copy */}
              <div className="flex items-center justify-between border-b border-white/5 px-6 py-2">
                <div className="flex items-center gap-2 text-xs text-slate-500">
                  <Cpu className="h-3 w-3" />
                  Generated by {current.model}
                </div>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 rounded px-2 py-1 text-xs text-slate-500 transition-colors hover:text-white"
                >
                  {copied ? (
                    <>
                      <Check className="h-3 w-3 text-green-400" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="h-3 w-3" />
                      Copy
                    </>
                  )}
                </button>
              </div>

              {/* Code */}
              <div className="code-block max-h-[500px] overflow-auto">
                <SyntaxHighlighter
                  language={current.language}
                  style={nightOwl}
                  customStyle={{
                    background: "transparent",
                    margin: 0,
                    padding: "1.5rem",
                    fontSize: "0.8125rem",
                  }}
                  showLineNumbers
                >
                  {current.response}
                </SyntaxHighlighter>
              </div>
            </motion.div>
          </AnimatePresence>
        </motion.div>
      </div>
    </section>
  );
}
